name: Intégration Continue PHP               # Nom du workflow

on:
  push:
    branches: [ main ]                       # Déclenché lors d’un push sur la branche main
  pull_request:
    branches: [ main ]                       # Déclenché lors d’une pull request vers main

jobs:
  build:                                     # Nom du job
    runs-on: ubuntu-latest                   # S’exécute sur la dernière version d’Ubuntu
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4            # 🔄 Utilise la version la plus récente de checkout

      - name: Installer PHP
        uses: shivammathur/setup-php@v2      # Installe PHP sur la machine virtuelle
        with:
          php-version: '8.3'                 
          coverage: none
          extensions: mbstring, intl

      - name: Installer les dépendances
        run: composer install --prefer-dist --no-progress --no-suggest  # Installe les dépendances PHP

      - name: Lancer les tests unitaires
        run: vendor/bin/phpunit --testdox  # Exécute les tests unitaires avec un affichage lisible\
      - name: Debug env
        run: |
          php -v
          composer --version
          composer show phpunit/phpunit || true
          ls -R
          cat composer.json